version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: kapkadibab/api_yamdb:latest
    restart: always
    container_name: web
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  static_value:
    driver: local
    driver_opts:
      o: bind
      type: ext4
      device: /www/static/
  media_value:
  db_value:
